[package]
name = "rustysynthplayer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rustysynthplayer"
path = "src/main.rs"

[dependencies]
rustysynth = "=1.3.6"
tinyaudio = "0.1.0"
itertools = "0.12"
clap = { version = "4.5", features = ["derive"] }